/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCowriteRouteImport } from './routes/api/cowrite'
import { Route as ApiQvacStatusRouteImport } from './routes/api/qvac-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCowriteRoute = ApiCowriteRouteImport.update({
  id: '/api/cowrite',
  path: '/api/cowrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQvacStatusRoute = ApiQvacStatusRouteImport.update({
  id: '/api/qvac-status',
  path: '/api/qvac-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cowrite': typeof ApiCowriteRoute
  '/api/qvac-status': typeof ApiQvacStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cowrite': typeof ApiCowriteRoute
  '/api/qvac-status': typeof ApiQvacStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cowrite': typeof ApiCowriteRoute
  '/api/qvac-status': typeof ApiQvacStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cowrite' | '/api/qvac-status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cowrite' | '/api/qvac-status'
  id: '__root__' | '/' | '/api/cowrite' | '/api/qvac-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCowriteRoute: typeof ApiCowriteRoute
  ApiQvacStatusRoute: typeof ApiQvacStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cowrite': {
      id: '/api/cowrite'
      path: '/api/cowrite'
      fullPath: '/api/cowrite'
      preLoaderRoute: typeof ApiCowriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qvac-status': {
      id: '/api/qvac-status'
      path: '/api/qvac-status'
      fullPath: '/api/qvac-status'
      preLoaderRoute: typeof ApiQvacStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCowriteRoute: ApiCowriteRoute,
  ApiQvacStatusRoute: ApiQvacStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
